POST http://localhost:10001/directors/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJvbiIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3NzEwNjAwfQ.DAxGdOZ1Zf6SABKrIV4TH9e5lzfXtyOYFHN2B9OIj3Y

{
  "name": "superka"
}

###

GET http://localhost:10001/directors/
Accept: application/json

###

GET http://localhost:10001/directors/5
Accept: application/json

###

PUT http://localhost:10001/directors/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJvbiIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3NzEwNjAwfQ.DAxGdOZ1Zf6SABKrIV4TH9e5lzfXtyOYFHN2B9OIj3Y

{
  "name": "kusturica"
}

###

DELETE http://localhost:10001/directors/21
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJvbiIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3NzEwNjAwfQ.DAxGdOZ1Zf6SABKrIV4TH9e5lzfXtyOYFHN2B9OIj3Y

###

PATCH http://localhost:10001/directors/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJvbiIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3NzEwNjAwfQ.DAxGdOZ1Zf6SABKrIV4TH9e5lzfXtyOYFHN2B9OIj3Y

{
  "name": "tintobrass"
}

###

GET http://localhost:10001/directors/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJvbiIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3NzEwNjAwfQ.DAxGdOZ1Zf6SABKrIV4TH9e5lzfXtyOYFHN2B9OIj3Y

###

GET http://localhost:10001/directors/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IlJvbiIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNjU3NzEwNjAwfQ.DAxGdOZ1Zf6SABKrIV4TH9e5lzfXtyOYFHN2B9OIj3Y

###